### ISSUE TITLE
Connection not possible

### ISSUE THREAD

**Issue by wawefr** [snegov/docker-seafile-client#2]
Hello
I hope you are well
I have a pb (see below) with the client.
For information 
         I use the Windows client Seafile with the sames paramaters it's OK
         I use your client with an over seafile host it's OK 
         When I use with my second seafile serveur KO I don't understand where is the problem
Thanks for your help
Fred

Creating seafile-client_seafile-client_1 ... done
Attaching to seafile-client_seafile-client_1
seafile-client_1  | Starting seafile daemon ...
seafile-client_1  | Started: seafile daemon ...
seafile-client_1  | Traceback (most recent call last):
seafile-client_1  |   File "/usr/bin/seaf-cli", line 1023, in <module>
seafile-client_1  |     main()
seafile-client_1  |   File "/usr/bin/seaf-cli", line 1019, in main
seafile-client_1  |     args.func(args)
seafile-client_1  |   File "/usr/bin/seaf-cli", line 675, in seaf_sync
seafile-client_1  |     token = get_token(url, username, password, tfa, conf_dir)
seafile-client_1  |   File "/usr/bin/seaf-cli", line 301, in get_token
seafile-client_1  |     token_json = urlopen("%s/api2/auth-token/" % url, data=data, headers=headers)
seafile-client_1  |   File "/usr/bin/seaf-cli", line 234, in urlopen
seafile-client_1  |     resp = urllib.request.urlopen(req)
seafile-client_1  |   File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
seafile-client_1  |     return opener.open(url, data, timeout)
seafile-client_1  |   File "/usr/lib/python3.7/urllib/request.py", line 531, in open
seafile-client_1  |     response = meth(req, response)
seafile-client_1  |   File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
seafile-client_1  |     'http', request, response, code, msg, hdrs)
seafile-client_1  |   File "/usr/lib/python3.7/urllib/request.py", line 569, in error
seafile-client_1  |     return self._call_chain(*args)
seafile-client_1  |   File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
seafile-client_1  |     result = func(*args)
seafile-client_1  |   File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
seafile-client_1  |     raise HTTPError(req.full_url, code, msg, hdrs, fp)
seafile-client_1  | urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by irrelevant-cookie** [comment]
Hi Fred,

Could you tell me, please, what is set as SERVER_HOST environment variable?

**Comment by wawefr** [comment]
Hi 
Many thanks for your help
You will find the docker compose for seafile server.
To complete I have a nginx proxy to access and I use cloudflare tunnel (My seafile server is "home hosted" )
Have a good day
Fred

version: '2.0'
services:
  db:
    image: mariadb
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=M*****
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - seafile-net

  memcached:
    image: memcached
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  seafile:
    image: seafileltd/seafile-mc
    container_name: seafile
    ports:
      - "8080:80"
    volumes:
      - /Data/seafile:/shared
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=M******
      - TIME_ZONE=Etc/UTC
      - SEAFILE_ADMIN_EMAIL=v**************
      - SEAFILE_ADMIN_PASSWORD=M*********
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=seafile.****************
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net

networks:
  seafile-net:

**Comment by irrelevant-cookie** [comment]
Sorry for the long response.
The docker-compose file seems normal. The issue might be caused by the configuration you mentioned, nginx with cloudflare tunnel - I guess, these scripts do not handle it well.
If the problem still exists, could you please create a test account for me on your server and send credentials to my email xxxxxxxxx? It would be much easier to debug it.
Thanks.
